/*
# Stackknit backend foundation retry

Creates the secure multi-role grocery data model and access rules. New tables are profiles, user_roles, categories, products, promotions, wishlists, carts, cart_items, addresses, orders, order_items, delivery_assignments, and payments. New accounts receive a customer role through an Auth trigger. Catalog writes are admin-controlled, warehouse staff manage inventory and fulfillment, delivery partners see assigned jobs, and customers only see their own commerce data. Order totals and stock changes are calculated server-side by create_order. RLS is enabled on every table and all remote functions have explicit grants.
*/

create extension if not exists pgcrypto;
do $$ begin create type public.app_role as enum ('admin','warehouse_manager','delivery_partner','customer'); exception when duplicate_object then null; end $$;
do $$ begin create type public.order_status as enum ('pending','confirmed','packed','ready_for_pickup','out_for_delivery','delivered','cancelled'); exception when duplicate_object then null; end $$;
do $$ begin create type public.payment_status as enum ('pending','authorized','paid','failed','refunded'); exception when duplicate_object then null; end $$;

create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade, full_name text not null default '', phone text not null default '', business_name text not null default '', avatar_url text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.user_roles (user_id uuid primary key references auth.users(id) on delete cascade, role public.app_role not null default 'customer', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.categories (id uuid primary key default gen_random_uuid(), name text not null, slug text not null unique, image_url text not null default '', description text not null default '', sort_order integer not null default 0, is_active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.products (id uuid primary key default gen_random_uuid(), category_id uuid references public.categories(id) on delete set null, brand text not null, name text not null, slug text not null unique, pack_size text not null, mrp numeric(12,2) not null check (mrp >= 0), wholesale_price numeric(12,2) not null check (wholesale_price >= 0 and wholesale_price <= mrp), moq integer not null default 1 check (moq > 0 and moq <= 10000), stock_quantity integer not null default 0 check (stock_quantity >= 0), image_url text not null default '', description text not null default '', rating numeric(3,2) not null default 0 check (rating between 0 and 5), is_active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.promotions (id uuid primary key default gen_random_uuid(), headline text not null, subtext text not null default '', cta_label text not null default 'Shop now', image_url text not null default '', background text not null default 'brand', badge text not null default '', sort_order integer not null default 0, is_active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.wishlists (user_id uuid not null default auth.uid() references auth.users(id) on delete cascade, product_id uuid not null references public.products(id) on delete cascade, created_at timestamptz not null default now(), primary key(user_id,product_id));
create table if not exists public.carts (id uuid primary key default gen_random_uuid(), user_id uuid not null unique default auth.uid() references auth.users(id) on delete cascade, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.cart_items (cart_id uuid not null references public.carts(id) on delete cascade, product_id uuid not null references public.products(id) on delete cascade, quantity integer not null check(quantity between 1 and 10000), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), primary key(cart_id,product_id));
create table if not exists public.addresses (id uuid primary key default gen_random_uuid(), user_id uuid not null default auth.uid() references auth.users(id) on delete cascade, label text not null default 'Business', recipient_name text not null, phone text not null, line1 text not null, line2 text not null default '', city text not null, state text not null, postal_code text not null, latitude numeric(10,7), longitude numeric(10,7), place_id text, is_default boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.orders (id uuid primary key default gen_random_uuid(), order_number text not null unique default ('SK-'||to_char(now(),'YYYY')||'-'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,8))), user_id uuid not null default auth.uid() references auth.users(id) on delete restrict, address_id uuid references public.addresses(id) on delete set null, status public.order_status not null default 'pending', subtotal numeric(12,2) not null default 0, discount numeric(12,2) not null default 0, delivery_fee numeric(12,2) not null default 0, total numeric(12,2) not null default 0, notes text not null default '', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.order_items (id uuid primary key default gen_random_uuid(), order_id uuid not null references public.orders(id) on delete cascade, product_id uuid references public.products(id) on delete set null, brand text not null, product_name text not null, pack_size text not null, unit_price numeric(12,2) not null check(unit_price >= 0), mrp numeric(12,2) not null check(mrp >= 0), quantity integer not null check(quantity > 0), line_total numeric(12,2) not null check(line_total >= 0), created_at timestamptz not null default now());
create table if not exists public.delivery_assignments (id uuid primary key default gen_random_uuid(), order_id uuid not null unique references public.orders(id) on delete cascade, delivery_partner_id uuid references auth.users(id) on delete set null, pickup_notes text not null default '', status public.order_status not null default 'ready_for_pickup', picked_up_at timestamptz, delivered_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.payments (id uuid primary key default gen_random_uuid(), order_id uuid not null unique references public.orders(id) on delete cascade, user_id uuid not null default auth.uid() references auth.users(id) on delete restrict, provider text not null default 'razorpay', provider_order_id text, provider_payment_id text, amount numeric(12,2) not null check(amount >= 0), status public.payment_status not null default 'pending', created_at timestamptz not null default now(), updated_at timestamptz not null default now());

create index if not exists products_category_active_idx on public.products(category_id,is_active) where is_active=true;
create index if not exists products_active_idx on public.products(is_active,created_at desc) where is_active=true;
create index if not exists orders_user_created_idx on public.orders(user_id,created_at desc);
create index if not exists orders_status_idx on public.orders(status,created_at desc);
create index if not exists delivery_partner_status_idx on public.delivery_assignments(delivery_partner_id,status);

create or replace function public.set_updated_at() returns trigger language plpgsql set search_path=public as $$ begin new.updated_at=now(); return new; end; $$;

do $$ declare t text; begin foreach t in array array['profiles','user_roles','categories','products','promotions','carts','cart_items','addresses','orders','delivery_assignments','payments'] loop execute format('drop trigger if exists %I_updated_at on public.%I',t,t); execute format('create trigger %I_updated_at before update on public.%I for each row execute function public.set_updated_at()',t,t); end loop; end $$;

create or replace function public.handle_new_auth_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,full_name,phone) values(new.id,coalesce(new.raw_user_meta_data->>'full_name',''),coalesce(new.phone,'')) on conflict(id) do nothing; insert into public.user_roles(user_id,role) values(new.id,'customer') on conflict(user_id) do nothing; insert into public.carts(user_id) values(new.id) on conflict(user_id) do nothing; return new; end; $$;
drop trigger if exists on_auth_user_created_stackknit on auth.users;
create trigger on_auth_user_created_stackknit after insert on auth.users for each row execute function public.handle_new_auth_user();

create or replace function public.has_role(p_role public.app_role) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.user_roles where user_id=auth.uid() and role=p_role); $$;
create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$ select public.has_role('admin'); $$;
create or replace function public.is_operations_staff() returns boolean language sql stable security definer set search_path=public as $$ select public.has_role('admin') or public.has_role('warehouse_manager'); $$;
create or replace function public.set_user_role(p_user_id uuid,p_role public.app_role) returns void language plpgsql security definer set search_path=public as $$ begin if not public.is_admin() then raise exception 'Not authorized'; end if; insert into public.user_roles(user_id,role) values(p_user_id,p_role) on conflict(user_id) do update set role=excluded.role,updated_at=now(); end; $$;

create or replace function public.create_order(p_address_id uuid,p_items jsonb) returns uuid language plpgsql security definer set search_path=public as $$ declare v_order_id uuid; v_item jsonb; v_product public.products%rowtype; v_qty integer; v_subtotal numeric(12,2):=0; v_discount numeric(12,2):=0; v_delivery numeric(12,2):=0; begin if auth.uid() is null then raise exception 'Authentication required'; end if; if not exists(select 1 from public.addresses where id=p_address_id and user_id=auth.uid()) then raise exception 'Invalid address'; end if; if jsonb_typeof(p_items)<>'array' or jsonb_array_length(p_items)=0 then raise exception 'Cart is empty'; end if; insert into public.orders(user_id,address_id) values(auth.uid(),p_address_id) returning id into v_order_id; for v_item in select value from jsonb_array_elements(p_items) loop v_qty:=(v_item->>'quantity')::integer; if v_qty is null or v_qty<1 or v_qty>10000 then raise exception 'Invalid quantity'; end if; select * into v_product from public.products where id=(v_item->>'product_id')::uuid and is_active=true for update; if not found or v_product.stock_quantity<v_qty then raise exception 'Product unavailable'; end if; v_subtotal:=v_subtotal+(v_product.wholesale_price*v_qty); v_discount:=v_discount+((v_product.mrp-v_product.wholesale_price)*v_qty); insert into public.order_items(order_id,product_id,brand,product_name,pack_size,unit_price,mrp,quantity,line_total) values(v_order_id,v_product.id,v_product.brand,v_product.name,v_product.pack_size,v_product.wholesale_price,v_product.mrp,v_qty,v_product.wholesale_price*v_qty); update public.products set stock_quantity=stock_quantity-v_qty where id=v_product.id; end loop; if v_subtotal<2000 then v_delivery:=80; end if; update public.orders set subtotal=v_subtotal,discount=v_discount,delivery_fee=v_delivery,total=v_subtotal+v_delivery where id=v_order_id; return v_order_id; exception when others then raise exception 'Could not create order'; end; $$;

revoke all on function public.set_user_role(uuid,public.app_role) from public,anon,authenticated; grant execute on function public.set_user_role(uuid,public.app_role) to authenticated;
revoke all on function public.create_order(uuid,jsonb) from public,anon; grant execute on function public.create_order(uuid,jsonb) to authenticated;
revoke all on function public.has_role(public.app_role) from public,anon; grant execute on function public.has_role(public.app_role) to authenticated;
revoke all on function public.is_admin() from public,anon; grant execute on function public.is_admin() to authenticated;
revoke all on function public.is_operations_staff() from public,anon; grant execute on function public.is_operations_staff() to authenticated;

alter table public.profiles enable row level security; alter table public.user_roles enable row level security; alter table public.categories enable row level security; alter table public.products enable row level security; alter table public.promotions enable row level security; alter table public.wishlists enable row level security; alter table public.carts enable row level security; alter table public.cart_items enable row level security; alter table public.addresses enable row level security; alter table public.orders enable row level security; alter table public.order_items enable row level security; alter table public.delivery_assignments enable row level security; alter table public.payments enable row level security;

 drop policy if exists profiles_select_own on public.profiles; create policy profiles_select_own on public.profiles for select to authenticated using(id=auth.uid() or public.is_admin());
 drop policy if exists profiles_update_own on public.profiles; create policy profiles_update_own on public.profiles for update to authenticated using(id=auth.uid()) with check(id=auth.uid());
 drop policy if exists roles_select_own_or_admin on public.user_roles; create policy roles_select_own_or_admin on public.user_roles for select to authenticated using(user_id=auth.uid() or public.is_admin());

 drop policy if exists categories_select_active on public.categories; create policy categories_select_active on public.categories for select to authenticated using(is_active or public.is_admin()); drop policy if exists categories_insert_admin on public.categories; create policy categories_insert_admin on public.categories for insert to authenticated with check(public.is_admin()); drop policy if exists categories_update_admin on public.categories; create policy categories_update_admin on public.categories for update to authenticated using(public.is_admin()) with check(public.is_admin()); drop policy if exists categories_delete_admin on public.categories; create policy categories_delete_admin on public.categories for delete to authenticated using(public.is_admin());
 drop policy if exists products_select_active on public.products; create policy products_select_active on public.products for select to authenticated using(is_active or public.is_admin()); drop policy if exists products_insert_admin on public.products; create policy products_insert_admin on public.products for insert to authenticated with check(public.is_admin()); drop policy if exists products_update_staff on public.products; create policy products_update_staff on public.products for update to authenticated using(public.is_admin() or public.has_role('warehouse_manager')) with check(public.is_admin() or public.has_role('warehouse_manager')); drop policy if exists products_delete_admin on public.products; create policy products_delete_admin on public.products for delete to authenticated using(public.is_admin());
 drop policy if exists promotions_select_active on public.promotions; create policy promotions_select_active on public.promotions for select to authenticated using(is_active or public.is_admin()); drop policy if exists promotions_insert_admin on public.promotions; create policy promotions_insert_admin on public.promotions for insert to authenticated with check(public.is_admin()); drop policy if exists promotions_update_admin on public.promotions; create policy promotions_update_admin on public.promotions for update to authenticated using(public.is_admin()) with check(public.is_admin()); drop policy if exists promotions_delete_admin on public.promotions; create policy promotions_delete_admin on public.promotions for delete to authenticated using(public.is_admin());

 drop policy if exists wishlists_select_own on public.wishlists; create policy wishlists_select_own on public.wishlists for select to authenticated using(user_id=auth.uid()); drop policy if exists wishlists_insert_own on public.wishlists; create policy wishlists_insert_own on public.wishlists for insert to authenticated with check(user_id=auth.uid()); drop policy if exists wishlists_delete_own on public.wishlists; create policy wishlists_delete_own on public.wishlists for delete to authenticated using(user_id=auth.uid());
 drop policy if exists carts_select_own on public.carts; create policy carts_select_own on public.carts for select to authenticated using(user_id=auth.uid()); drop policy if exists carts_update_own on public.carts; create policy carts_update_own on public.carts for update to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
 drop policy if exists cart_items_select_own on public.cart_items; create policy cart_items_select_own on public.cart_items for select to authenticated using(exists(select 1 from public.carts c where c.id=cart_id and c.user_id=auth.uid())); drop policy if exists cart_items_insert_own on public.cart_items; create policy cart_items_insert_own on public.cart_items for insert to authenticated with check(exists(select 1 from public.carts c where c.id=cart_id and c.user_id=auth.uid())); drop policy if exists cart_items_update_own on public.cart_items; create policy cart_items_update_own on public.cart_items for update to authenticated using(exists(select 1 from public.carts c where c.id=cart_id and c.user_id=auth.uid())) with check(exists(select 1 from public.carts c where c.id=cart_id and c.user_id=auth.uid())); drop policy if exists cart_items_delete_own on public.cart_items; create policy cart_items_delete_own on public.cart_items for delete to authenticated using(exists(select 1 from public.carts c where c.id=cart_id and c.user_id=auth.uid()));
 drop policy if exists addresses_select_own on public.addresses; create policy addresses_select_own on public.addresses for select to authenticated using(user_id=auth.uid()); drop policy if exists addresses_insert_own on public.addresses; create policy addresses_insert_own on public.addresses for insert to authenticated with check(user_id=auth.uid()); drop policy if exists addresses_update_own on public.addresses; create policy addresses_update_own on public.addresses for update to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid()); drop policy if exists addresses_delete_own on public.addresses; create policy addresses_delete_own on public.addresses for delete to authenticated using(user_id=auth.uid());
 drop policy if exists orders_select_allowed on public.orders; create policy orders_select_allowed on public.orders for select to authenticated using(user_id=auth.uid() or public.is_operations_staff() or exists(select 1 from public.delivery_assignments d where d.order_id=orders.id and d.delivery_partner_id=auth.uid()));
 drop policy if exists order_items_select_allowed on public.order_items; create policy order_items_select_allowed on public.order_items for select to authenticated using(exists(select 1 from public.orders o where o.id=order_id and (o.user_id=auth.uid() or public.is_operations_staff() or exists(select 1 from public.delivery_assignments d where d.order_id=o.id and d.delivery_partner_id=auth.uid()))));
 drop policy if exists delivery_select_allowed on public.delivery_assignments; create policy delivery_select_allowed on public.delivery_assignments for select to authenticated using(delivery_partner_id=auth.uid() or public.is_operations_staff()); drop policy if exists delivery_insert_staff on public.delivery_assignments; create policy delivery_insert_staff on public.delivery_assignments for insert to authenticated with check(public.is_operations_staff()); drop policy if exists delivery_update_allowed on public.delivery_assignments; create policy delivery_update_allowed on public.delivery_assignments for update to authenticated using(delivery_partner_id=auth.uid() or public.is_operations_staff()) with check(delivery_partner_id=auth.uid() or public.is_operations_staff());
 drop policy if exists payments_select_own on public.payments; create policy payments_select_own on public.payments for select to authenticated using(user_id=auth.uid() or public.is_admin());
 revoke insert,update,delete on public.orders from authenticated; revoke insert,update,delete on public.order_items from authenticated; revoke insert,update,delete on public.payments from authenticated; revoke update on public.user_roles from authenticated;
